const constant = {
  DEFAULT_REVIEW_TEXT_BANK: [
    "Rất thích cách chăm sóc khách hàng của bên shop. Chất lượng sp là 1 phần lớn nhưng có thể khi mua người ta mua cả cái tâm của người bán. Shop hướng dẫn rất tận tình. Sẽ ủng hộ shop dài giao hàng nhanh đóng gói cẩn thận giá sản phẩm rẻ hơn nhiều shop khác",
    "Sp chất lượng lắm ! Shop gói hàng cẩn thận, giao hàng rất nhanh . Giá rẻ hơn những chỗ khác. Các bạn yên tâm mua nhé",
    "Mình chưa dùng nhưng cách shop tư vấn rất nhiệt tình & thật tâm chứ k phải muốn bán cho dc hang. Đủ để cho 5 sao",
    "Chất lượng sản phẩm tuyệt vời Đóng gói sàn phẩm rất đẹp và chắc chắn Shop phục vụ tốt Rất đáng tiền Thời gian giao hàng nhanh",
    "Chất lượng rất ổn so với tầm giá, shop đóng gói đẹp và chắc chắn, thời gian giao hàng cũng cực nhanh.",
    "Rất là chim ưng, sản phẩm tốt lắm, trả lời cũng nhiệt tình nhẹ nhàng, mọi người nên mua dùng thử nhé ^ ^",
    "Chưa thấy shop nào nhiệt tình như thế này ạ, giải đáp mọi thắc mắc của mình. Chất lượng lại cực kỳ tốt, giá lại rất ổn so với các bên khác. Nếu có đánh giá 10 sao cũng cho shop luôn.",
    "Giao hàng nhanh, hàng nhận chất lượng y như hình và clip quảng cáo. Sẽ ủng hộ shop những lần tới và đánh giá 5 sao",
    "Giao hàng nhanh, đóng gói cẩn thận, mua của shop rồi thấy ưng nên mua thêm cho người nhà nữa.",
    "Lần trước mua ok nên lần này quyết định mua tiếp. Sản phẩm y hình, giao hàng nhanh, đóng gói cẩn thận, sẽ ủng hộ shop dài dài nữa.",
    "Tôi muốn khẳng định với các bạn là sản phẩm của shop rất tốt so với giá tiền, sẽ ủng hộ shop dài dài luôn nhen.",
    "Shop làm ăn uy tín lắm luôn. Nếu cần mua j nhất định lại ghé shop ủng hộ. Cám ơn shop rất nhiều. Lòng tin không đặt nhậm chỗ là đấy, phải nói là chất lượng quá ok luôn.",
    "Chất lượng sản phẩm tốt, đóng gói cẩn thận lại hàng nhanh, mình sẽ ủng hộ shop tiếp.",
    "Hàng chất đỉnh luôn !! Cái gì cũng ưng và đẹp, shop cực kỳ nhiệt tình và dễ thương ! ",
    "Rất thích cách chăm sóc khách hàng của bên shop. Chất lượng sp là 1 phần lớn nhưng có thể khi mua người ta mua cả cái tâm của người bán. Shop hướng dẫn rất tận tình. Sẽ ủng hộ shop dài",
    "Giao hàng nhanh, shop tư vấn nhiệt tình, chất lượng ok, có nhu cầu sẽ ủng hộ shop tiếp",
    "Đã nhân hàng và dùng thử, tương đối ổn định, giá chấp nhận dc so với chất lượng",
    "Hàng dùng ngon sợ với tầm giá quá rẻ, nói chung là ok lắm ạ!",
    "Giao hàng nhanh. Đóng gói ổn. Giá rẻ. Sẽ ủng hộ tiếp nếu có nhu cầu",
    "Giao hàng siêu nhanh, chất lượng sp tốt hơn mong đợi, mong là shop có dịch vụ bảo hành tốt",
    "Rất ưng,đóng hàng chắc chắn .lần sau sẽ tiếp tục ủng hộ shop",
    "Đã test rất ok. Giao hàng nhanh, hàng mới 100% .đóng gói cẩn thận. Giá thành rẻ hơn shop khác mấy chục. QUá tuyệt",
    "Giao hàng nhanh nha.Sẽ ủng hộ lần sau nè",
    "Sản phẩm khá ok ạ . Shop giao hàng nhanh , chất lượng 5 sao cho shop ạ . Cám ơn shop nhé",
    "Shop bọc hàng kỹ quá, loay hoay mãi mới mở ra đc. Chất lượng hàng tốt nha. Sẽ ủng hộ shop nữa",
    "Shop bọc hàng kỹ quá, loay hoay mãi mới mở ra đc. Chất lượng hàng tốt nha. Sẽ ủng hộ shop nữa",
    "Hàng rất đẹp nha, mua được giá sale nên rất thích, giao hàng nhanh chóng và sẽ ủng hộ shop nhé",
  ],
   IMAGES_NAME_BANK: [
    "294-536x354.jpg",
    "667-536x354.jpg",
    "910-536x354.jpg",
    "527-536x354.jpg",
    "472-536x354.jpg",
    "35-536x354.jpg",
    "337-536x354.jpg",
    "391-536x354.jpg",
    "457-536x354.jpg",
    "350-536x354.jpg",
    "361-536x354.jpg",
    "698-536x354.jpg",
    "115-536x354.jpg",
    "198-536x354.jpg",
  ],
   DEFAULT_PATH = "C:\\Users\\Tuan17\\Downloads\\"
  
}
export default constant